/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthConfirmSignUpForm: typeof import('./src/components/auth/ConfirmSignUpForm.vue')['default']
    AuthLoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    AuthRegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    AuthRegistrationForm: typeof import('./src/components/auth/RegistrationForm.vue')['default']
    AuthScaffold: typeof import('./src/components/auth/Scaffold.vue')['default']
    AuthSignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    AuthSignUp: typeof import('./src/components/auth/SignUp.vue')['default']
    AuthSignupForm: typeof import('./src/components/auth/SignupForm.vue')['default']
    AuthSignUpForm: typeof import('./src/components/auth/SignUpForm.vue')['default']
    AuthSignUpFormConfirm: typeof import('./src/components/auth/SignUpFormConfirm.vue')['default']
    AuthVerificationForm: typeof import('./src/components/auth/VerificationForm.vue')['default']
    copy: typeof import('./src/components/auth/RegistrationForm copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scaffold: typeof import('./src/components/scaffold.vue')['default']
    SignUp: typeof import('./src/components/signUp/index.vue')['default']
    Ui: typeof import('./src/components/ui/Index.vue')['default']
    UiButton: typeof import('./src/components/ui/Button.vue')['default']
    UiForm: typeof import('./src/components/ui/Form.vue')['default']
    UiInput: typeof import('./src/components/ui/Input.vue')['default']
  }
}
